<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\process.ico</ApplicationIcon>
    <StartupObject>ProcessManagerApp.App</StartupObject>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\net8.0-windows\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\net8.0-windows\</OutputPath>
    <DefineConstants>RELEASE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <Resource Include="**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\process.ico" />
    <EmbeddedResource Include="Resources\warning.ico" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
    <Page Include="Views\MainWindow.xaml" />
    <Page Include="Views\Styles.xaml" />
    <Compile Include="Views\Converters\*.cs" />
    <Compile Include="Views\MainWindow.xaml.cs" />
    <Compile Include="ViewModels\*.cs" />
    <Compile Include="Models\*.cs" />
    <Compile Include="Services\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Windows" Version="8.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

</Project>
